services:
  why3:
    build:
      context: "."
      dockerfile: "./docker/why3/Dockerfile"
      network: "host"
    volumes:
      - ".:/workspace"
      # WSLg
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/mnt/wslg:/mnt/wslg"
    environment:
      # WSLg
      - "DISPLAY=$DISPLAY"
      - "WAYLAND_DISPLAY=$WAYLAND_DISPLAY"
      - "XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR"
      - "PULSE_SERVER=$PULSE_SERVER"
