services:
  why3:
    build:
      context: "."
      dockerfile: "./docker/why3/Dockerfile"
      network: "host"
    volumes:
      - type: "bind"
        source: "."
        target: "/workspace"
      - type: "volume"
        source: "creusot_prelude"
        target: "/workspace/prelude"
      # WSLg
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/mnt/wslg:/mnt/wslg"
    environment:
      # WSLg
      - "DISPLAY"
      - "WAYLAND_DISPLAY"
      - "XDG_RUNTIME_DIR"
      - "PULSE_SERVER"

volumes:
  creusot_prelude:
